[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "ros-code-standard-uncrustify"
version = "0.78.1"
description = "Static uncrustify binary and ROS 2 code style checker/formatter for manylint"
readme = "README.md"
requires-python = ">=3.8"
license = { text = "Apache-2.0" }
dependencies = []

[project.scripts]
ros-code-standard-uncrustify = "ros_code_standard_uncrustify.cli:main"

[tool.hatch.build.targets.wheel]
packages = ["src/ros_code_standard_uncrustify"]
dev-mode-dirs = ["src"]
artifacts = [
    "src/ros_code_standard_uncrustify/bin/uncrustify",
    "src/ros_code_standard_uncrustify/configuration/*.cfg",
]

[tool.hatch.build.targets.wheel.hooks.custom]
path = "hatch_build.py"
